[phases.setup]
aptPkgs = ["python3-dev", "python3-pip", "libjpeg-dev", "libpng-dev", "zlib1g-dev", "python3-setuptools", "python3-wheel", "gcc"]
nixPkgs = ['python311']
[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements/prod.txt']